const maleAgeData = [
  {
    state: 'North',
    fourWheels: 6.7,
    tenWheels: 28.6,
    sixWheels: 5.1,
    etWheels: 6.7,
    semi: 28.6,
    ftyTrailer: 5.1,
    twTrailer: 6.7,
    twWheels: 28.6,
    tractorHeadTruck: 5.1,
    bikeCarrierTruck: 5.1,
  },
  {
    state: 'South',
    fourWheels: 6.7,
    tenWheels: 28.6,
    sixWheels: 5.1,
    etWheels: 6.7,
    semi: 28.6,
    ftyTrailer: 5.1,
    twTrailer: 6.7,
    twWheels: 28.6,
    tractorHeadTruck: 5.1,
    bikeCarrierTruck: 5.1,
  },
  {
    state: 'Northeast',
    fourWheels: 6.7,
    tenWheels: 28.6,
    sixWheels: 5.1,
    etWheels: 6.7,
    semi: 28.6,
    ftyTrailer: 5.1,
    twTrailer: 6.7,
    twWheels: 28.6,
    tractorHeadTruck: 5.1,
    bikeCarrierTruck: 5.1,
  },
  {
    state: 'Western',
    fourWheels: 6.7,
    tenWheels: 28.6,
    sixWheels: 5.1,
    etWheels: 6.7,
    semi: 28.6,
    ftyTrailer: 5.1,
    twTrailer: 6.7,
    twWheels: 28.6,
    tractorHeadTruck: 5.1,
    bikeCarrierTruck: 5.1,
  },
  {
    state: 'Central',
    fourWheels: 6.7,
    tenWheels: 28.6,
    sixWheels: 5.1,
    etWheels: 6.7,
    semi: 28.6,
    ftyTrailer: 5.1,
    twTrailer: 6.7,
    twWheels: 28.6,
    tractorHeadTruck: 5.1,
    bikeCarrierTruck: 5.1,
  },
  {
    state: 'Eastern',
    fourWheels: 6.7,
    tenWheels: 28.6,
    sixWheels: 5.1,
    etWheels: 6.7,
    semi: 28.6,
    ftyTrailer: 5.1,
    twTrailer: 6.7,
    twWheels: 28.6,
    tractorHeadTruck: 5.1,
    bikeCarrierTruck: 5.1,
  },
];

export default {
  getMaleAgeData() {
    return maleAgeData;
  },
};
