export const populationData: any = [
  {
    state: 'Various kinds',
    Western: 6.7,
    Central: 28.6,
    Eastern: 5.1,
    North: 6.7,
    South: 28.6,
    Northeast: 5.1,
  },
  {
    state: 'Construction',
    Western: 6.7,
    Central: 28.6,
    Eastern: 5.1,
    North: 6.7,
    South: 28.6,
    Northeast: 5.1,
  },
  {
    state: 'Agriculture products',
    Western: 6.7,
    Central: 28.6,
    Eastern: 5.1,
    North: 26.7,
    South: 28.6,
    Northeast: 5.1,
  },
  {
    state: 'Foods and foodstuffs',
    Western: 6.7,
    Central: 28.6,
    Eastern: 5.1,
    North: 46.7,
    South: 28.6,
    Northeast: 5.1,
  },
  {
    state: 'Consumer goods',
    Western: 6.7,
    Central: 28.6,
    Eastern: 45.1,
    North: 6.7,
    South: 28.6,
    Northeast: 25.1,
  },
  {
    state: 'Furniture',
    Western: 6.7,
    Central: 28.6,
    Eastern: 5.1,
    North: 16.7,
    South: 28.6,
    Northeast: 5.1,
  },
  {
    state: 'Clothes',
    Western: 6.7,
    Central: 28.6,
    Eastern: 15.1,
    North: 6.7,
    South: 8.6,
    Northeast: 5.1,
  },
  {
    state: 'Electronic devices',
    Western: 6.7,
    Central: 28.6,
    Eastern: 5.1,
    North: 6.7,
    South: 2.6,
    Northeast: 5.1,
  },
  {
    state: 'Machinery',
    Western: 6.7,
    Central: 38.6,
    Eastern: 5.1,
    North: 6.7,
    South: 27.6,
    Northeast: 5.1,
  },
  {
    state: 'Fertilizer',
    Western: 4.7,
    Central: 8.6,
    Eastern: 5.1,
    North: 6.7,
    South: 5.6,
    Northeast: 5.1,
  },
  {
    state: 'Chemical products',
    Western: 5.7,
    Central: 8.6,
    Eastern: 6.1,
    North: 6.7,
    South: 7.6,
    Northeast: 5.1,
  },
  {
    state: 'Liquid goods',
    Western: 4.7,
    Central: 8.6,
    Eastern: 20.1,
    North: 6.7,
    South: 5.6,
    Northeast: 5.1,
  },
  {
    state: 'Oil / gas',
    Western: 5.7,
    Central: 8.6,
    Eastern: 5.1,
    North: 6.7,
    South: 5.6,
    Northeast: 5.1,
  },
  {
    state: 'Wood',
    Western: 4.7,
    Central: 4.6,
    Eastern: 5.1,
    North: 6.7,
    South: 1.6,
    Northeast: 5.1,
  },
  {
    state: 'Pharmaceutical products',
    Western: 4.7,
    Central: 4.6,
    Eastern: 5.1,
    North: 16.7,
    South: 10.6,
    Northeast: 5.1,
  },
  {
    state: 'Refrigerated products',
    Western: 14.7,
    Central: 4.6,
    Eastern: 5.1,
    North: 6.7,
    South: 10.6,
    Northeast: 5.1,
  },
  {
    state: 'Other',
    Western: 4.7,
    Central: 14.6,
    Eastern: 5.1,
    North: 6.7,
    South: 10.6,
    Northeast: 5.1,
  },
  {
    state: 'Beverage',
    Western: 4.7,
    Central: 4.6,
    Eastern: 25.1,
    North: 6.7,
    South: 10.6,
    Northeast: 5.1,
  },
  {
    state: 'Dried foods',
    Western: 4.7,
    Central: 4.6,
    Eastern: 5.1,
    North: 16.7,
    South: 1.6,
    Northeast: 7.1,
  },
  {
    state: 'Frozen foods',
    Western: 4.7,
    Central: 4.6,
    Eastern: 5.1,
    North: 6.7,
    South: 10.6,
    Northeast: 5.1,
  },
  {
    state: 'Appliances',
    Western: 14.7,
    Central: 4.6,
    Eastern: 5.1,
    North: 6.7,
    South: 5.6,
    Northeast: 5.1,
  },
  {
    state: 'Agrochemical',
    Western: 4.7,
    Central: 4.6,
    Eastern: 15.1,
    North: 6.7,
    South: 1.6,
    Northeast: 5.1,
  },
  {
    state: 'Vehicles',
    Western: 4.7,
    Central: 4.6,
    Eastern: 5.1,
    North: 1.7,
    South: 1.6,
    Northeast: 5.1,
  },
  {
    state: 'Steel',
    Western: 4.7,
    Central: 4.6,
    Eastern: 5.1,
    North: 1.7,
    South: 1.6,
    Northeast: 5.1,
  },
  {
    state: 'Fresh foods',
    Western: 4.7,
    Central: 4.6,
    Eastern: 5.1,
    North: 1.7,
    South: 1.6,
    Northeast: 5.1,
  },
  {
    state: 'Industrial products',
    Western: 4.7,
    Central: 4.6,
    Eastern: 5.1,
    North: 1.7,
    South: 1.6,
    Northeast: 5.1,
  },
];

export default {
  getMaleAgeData() {
    return populationData;
  },
};
